config/routes.rb
Rails.application.routes.draw do
  resources :shelves
  get "/auth/oauth2/callback" => "auth0#callback"
  get "/auth/failure" => "auth0#failure"
  get "/dashboard" => "dashboard#show"
  get "/logout/logout" => "logout#logout"
  root "home#show"
  resources :books
  resources :publishers
  resources :authors
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/publisher.rb
class Publisher < ApplicationRecord
    has_many :books, dependent: :destroy
end

app/controllers/publishers_controller.rb
class PublishersController < ApplicationController
  before_action :set_publisher, only: [:show, :edit, :update, :destroy]

  # GET /publishers
  # GET /publishers.json
  def index
    @publishers = Publisher.all
  end

  # GET /publishers/1
  # GET /publishers/1.json
  def show
  end

  # GET /publishers/new
  def new
    @publisher = Publisher.new
  end

  # GET /publishers/1/edit
  def edit
  end

  # POST /publishers
  # POST /publishers.json
  def create
    @publisher = Publisher.new(publisher_params)

    respond_to do |format|
      if @publisher.save
        format.html { redirect_to @publisher, notice: 'Publisher was successfully created.' }
        format.json { render :show, status: :created, location: @publisher }
      else
        format.html { render :new }
        format.json { render json: @publisher.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /publishers/1
  # PATCH/PUT /publishers/1.json
  def update
    respond_to do |format|
      if @publisher.update(publisher_params)
        format.html { redirect_to @publisher, notice: 'Publisher was successfully updated.' }
        format.json { render :show, status: :ok, location: @publisher }
      else
        format.html { render :edit }
        format.json { render json: @publisher.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /publishers/1
  # DELETE /publishers/1.json
  def destroy
    @publisher.destroy
    respond_to do |format|
      format.html { redirect_to publishers_url, notice: 'Publisher was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_publisher
      @publisher = Publisher.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def publisher_params
      params.require(:publisher).permit(:name)
    end
end

app/helpers/publishers_helper.rb
module PublishersHelper
end

app/views/publishers/_form.html.erb
<%= form_with(model: publisher, local: true) do |form| %>
  <% if publisher.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(publisher.errors.count, "error") %> prohibited this publisher from being saved:</h2>

      <ul>
      <% publisher.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :publisher_name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/publishers/edit.html.erb
<h1>Editing Publisher</h1>

<%= render 'form', publisher: @publisher %>

<%= link_to 'Show', @publisher %> |
<%= link_to 'Back', publishers_path %>

app/views/publishers/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Publishers</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @publishers.each do |publisher| %>
      <tr>
        <td><%= publisher.name %></td>
        <td><%= link_to 'Show', publisher %></td>
        <td><%= link_to 'Edit', edit_publisher_path(publisher) %></td>
        <td><%= link_to 'Destroy', publisher, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Publisher', new_publisher_path %>

app/views/publishers/new.html.erb
<h1>New Publisher</h1>

<%= render 'form', publisher: @publisher %>

<%= link_to 'Back', publishers_path %>

app/views/publishers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @publisher.name %>
</p>

<%= link_to 'Edit', edit_publisher_path(@publisher) %> |
<%= link_to 'Back', publishers_path %>