config/routes.rb
Rails.application.routes.draw do
  resources :shelves
  get "/auth/oauth2/callback" => "auth0#callback"
  get "/auth/failure" => "auth0#failure"
  get "/dashboard" => "dashboard#show"
  get "/logout/logout" => "logout#logout"
  root "home#show"
  resources :books
  resources :publishers
  resources :authors
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :author
  belongs_to :publisher
  has_many :shelves, dependent: :destroy
  has_many :users, through: :shelves
  scope :by_user, ->(user) { where(user_id: user.id)}
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :authenticate_user!, except: [:index,:show]
  before_action :set_book, only: [:show, :edit, :update, :destroy]

  # GET /books
  # GET /books.json
  def index
    @books = Book.all
  end

  # GET /books/1
  # GET /books/1.json
  def show
    @current_shelf=@book.shelves.by_user(current_user)
    if @current_shelf.blank?
      @shelf=Shelf.new
      @place=""
    else 
      @shelf=@current_shelf
      @place=@shelf.place

    end 
  end

  # GET /books/new
  def new
    @book = Book.new
  end

  # GET /books/1/edit
  def edit
  end

  # POST /books
  # POST /books.json
  def create
    logger.debug params
    @author=Author.find_or_create_by(name: params[:book][:author_id])
    @publisher=Publisher.find_or_create_by(name: params[:book][:publisher_id])
    @book = Book.new(book_params)
    @book.author_id=@author.id
    @book.publisher_id=@publisher.id
    respond_to do |format|
      if @book.save
        format.html { redirect_to @book, notice: 'Book was successfully created.' }
        format.json { render :show, status: :created, location: @book }
      else
        format.html { render :new }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /books/1
  # PATCH/PUT /books/1.json
  def update
    respond_to do |format|
      if @book.update(book_params)
        format.html { redirect_to @book, notice: 'Book was successfully updated.' }
        format.json { render :show, status: :ok, location: @book }
      else
        format.html { render :edit }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /books/1
  # DELETE /books/1.json
  def destroy
    @book.destroy
    respond_to do |format|
      format.html { redirect_to books_url, notice: 'Book was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_book
      @book = Book.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def book_params
      params.require(:book).permit(:title, :isbn, :author_id, :publisher_id)
    end
end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/books/_form.html.erb
<%= form_with(model: book, local: true) do |form| %>
  <% if book.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(book.errors.count, "error") %> prohibited this book from being saved:</h2>

      <ul>
      <% book.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title, id: :book_title %>
  </div>

  <div class="field">
    <%= form.label :isbn %>
    <%= form.text_field :isbn, id: :book_isbn %>
  </div>

  <div class="field">
    <%= form.label :author_id %>
    <%= form.text_field :author_id, id: :book_author_id %>
  </div>

  <div class="field">
    <%= form.label :publisher_id %>
    <%= form.text_field :publisher_id, id: :book_publisher_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/books/edit.html.erb
<h1>Editing Book</h1>

<%= render 'form', book: @book %>

<%= link_to 'Show', @book %> |
<%= link_to 'Back', books_path %>

app/views/books/index.html.erb
<p id="notice"><%= notice %></p>
<div class="container">
<header class="book_list_header">
<h1>Books</h1>
<% if user_signed_in? %>
<%= link_to '+', new_book_path,class: "btn btn-circle btn-success" %>
<% else %>
<%= link_to 'Login to add a new book',"/auth/auth0" %>
<% end %>
</header>
<ul class="book_list">
    <% @books.each do |book| %>
      <li class="book_entry">
        <h2><%= book.title %></h2>
        <div class="isbn"><%= book.isbn %></div>
        <div class="author"><%= book.author.name %></div >
        <div class="publisher"><%= book.publisher.name %></div >
        <div class="actions"><%= link_to 'Show', book %>
        <%= link_to 'Edit', edit_book_path(book) %>
        <%= link_to 'Destroy', book, method: :delete, data: { confirm: 'Are you sure?' } %></div>
      </li>
    <% end %>
</ul>
</div>
<br>

app/views/books/new.html.erb
<h1>New Book</h1>

<%= render 'form', book: @book %>

<%= link_to 'Back', books_path %>

app/views/books/show.html.erb
<p id="notice"><%= notice %></p>
<article class="jumbotron">
<h1><%= @book.title %></h1>

<p>
  <strong>Isbn:</strong>
  <%= @book.isbn %>
</p>

<p>
  <strong>Author:</strong>
  <%= @book.author.name %>
</p>

<p>
  <strong>Publisher:</strong>
  <%= @book.publisher.name %>
</p>
<%= form_with(model: @shelf, local: true) do |form| %>

  <div class="field">
    <%= form.label :place,"Shelf"%>
    <%= form.select(:place,options_for_select(Shelf.places.keys),:selected=>@place,:include_blank=>true,id: :shelf_place) 
    %>
  </div>
  <%= form.hidden_field :book_id, :value=>params[:id] %>
  <div class="actions">
    <%= form.submit "Move to shelf" %>
  </div>
<% end %>
<%= link_to 'Edit', edit_book_path(@book) %> |
<%= link_to 'Back', books_path %>
</article>