config/routes.rb
Rails.application.routes.draw do
  resources :shelves
  get "/auth/oauth2/callback" => "auth0#callback"
  get "/auth/failure" => "auth0#failure"
  get "/dashboard" => "dashboard#show"
  get "/logout/logout" => "logout#logout"
  root "home#show"
  resources :books
  resources :publishers
  resources :authors
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/author.rb
class Author < ApplicationRecord
    has_many :books, dependent: :destroy
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :author
  belongs_to :publisher
  has_many :shelves, dependent: :destroy
  has_many :users, through: :shelves
  scope :by_user, ->(user) { where(user_id: user.id)}
end

app/models/publisher.rb
class Publisher < ApplicationRecord
    has_many :books, dependent: :destroy
end

app/models/shelf.rb
class Shelf < ApplicationRecord
  enum place: [:wishlist, :bought, :reading, :done]
  belongs_to :user
  belongs_to :book
  validates :user_id, uniqueness: {scope: :book_id}
  scope :by_user, ->(user) { where(user_id: user)}
  
end

app/models/user.rb
class User < ApplicationRecord
    attr_accessor :info
    has_many :shelves, dependent: :destroy
    has_many :books, through: :shelves
end

app/controllers/auth0_controller.rb
class Auth0Controller < ApplicationController
  def callback
    # This stores all the user information that came from Auth0
    # and the IdP
    session[:userinfo] = request.env['omniauth.auth']

    # Redirect to the URL you want after successful auth
    redirect_to '/books'
  end

  def failure
    # show a failure page or redirect to an error page
    @error_msg = request.params['message']
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :authenticate_user!, except: [:index,:show]
  before_action :set_book, only: [:show, :edit, :update, :destroy]

  # GET /books
  # GET /books.json
  def index
    @books = Book.all
  end

  # GET /books/1
  # GET /books/1.json
  def show
    @current_shelf=@book.shelves.by_user(current_user)
    if @current_shelf.blank?
      @shelf=Shelf.new
      @place=""
    else 
      @shelf=@current_shelf
      @place=@shelf.place

    end 
  end

  # GET /books/new
  def new
    @book = Book.new
  end

  # GET /books/1/edit
  def edit
  end

  # POST /books
  # POST /books.json
  def create
    logger.debug params
    @author=Author.find_or_create_by(name: params[:book][:author_id])
    @publisher=Publisher.find_or_create_by(name: params[:book][:publisher_id])
    @book = Book.new(book_params)
    @book.author_id=@author.id
    @book.publisher_id=@publisher.id
    respond_to do |format|
      if @book.save
        format.html { redirect_to @book, notice: 'Book was successfully created.' }
        format.json { render :show, status: :created, location: @book }
      else
        format.html { render :new }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /books/1
  # PATCH/PUT /books/1.json
  def update
    respond_to do |format|
      if @book.update(book_params)
        format.html { redirect_to @book, notice: 'Book was successfully updated.' }
        format.json { render :show, status: :ok, location: @book }
      else
        format.html { render :edit }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /books/1
  # DELETE /books/1.json
  def destroy
    @book.destroy
    respond_to do |format|
      format.html { redirect_to books_url, notice: 'Book was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_book
      @book = Book.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def book_params
      params.require(:book).permit(:title, :isbn, :author_id, :publisher_id)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
    def show
    end
end

app/controllers/logout_controller.rb
class LogoutController < ApplicationController
    include LogoutHelper
    def logout
        reset_session
        redirect_to logout_url.to_s
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
    
end

app/helpers/auth0_helper.rb
module Auth0Helper
    private
    def user_signed_in?
        session[:userinfo].present?
    end
    
    def authenticate_user!
        if user_signed_in?
            @auth0_user=session[:userinfo]
            email_id=@auth0_user["info"]["email"]
            @current_user=User.find_or_create_by!(email: email_id)
            @current_user.info=@auth0_user["info"]
        else
            redirect_to login_path
        end
    end
    
    def current_user
        @current_user
    end
    
    def login_path
        root_path
    end
end

app/helpers/authors_helper.rb
module AuthorsHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/logout_helper.rb
module LogoutHelper
    def logout_url
        domain = Rails.application.secrets.auth0_domain
        client_id = Rails.application.secrets.auth0_client_id
        request_params = {
            returnTo: root_url,
            client_id: client_id
        }

        URI::HTTPS.build(host: domain, path: '/logout', query: to_query(request_params))
    end

    private

    def to_query(hash)
        hash.map { |k, v| "#{k}=#{URI.escape(v)}" unless v.nil? }.reject(&:nil?).join('&')
    end
end

app/helpers/publishers_helper.rb
module PublishersHelper
end

app/helpers/session_helper.rb
module SessionHelper
  def get_state
    state = SecureRandom.hex(24)
    session['omniauth.state'] = state

    state
  end
end

app/helpers/shelves_helper.rb
module ShelvesHelper
end

app/views/layouts/_navbar.html.erb
<nav class="navbar">
<div class="brand-info"> 
<%= image_tag "book.svg",class: "logo-image" %>
<div class="title">BookShelf</div>
</div>
<ul class="topnav">
<% if user_signed_in? %>
<li class="nav-list-item"><%= link_to "Profile",dashboard_path, class: "nav-item" %></li>
<li class="nav-list-item"><%= link_to "Logout",logout_logout_path,class: "nav-item" %></li> 
<% else %>
<li class="nav-list-item"><a class="nav-item" href="/auth/auth0">Login</a></li>
<% end %>
</ul>
</nav>

app/views/layouts/_shelves.html.erb
<aside>
    <% if user_signed_in? %>
    <section class="shelves">
        <%= link_to "All",books_path %>
        <%= link_to "Wish List",shelves_path(place: "wishlist") %>
        <%= link_to "Bought",shelves_path(place: "bought") %>
        <%= link_to "Reading",shelves_path(place: "reading") %>
        <%= link_to "Done",shelves_path(place: "done") %>
    </section>
    <% end %>
</aside>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Auth0app</title>
    <%= csrf_meta_tags %>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header><%= render 'layouts/navbar' %></header>
    <%= render 'layouts/shelves' %>
    <%= yield %>
  </body>
</html>